 import { Plant } from './plant';
 
 export const PLANTS: Plant[] = [
     { id: 1, name: 'cyclamen', type: 'flowers', image: 'img/cyclamen.jpg', 
        description: 'Cyclamen is a genus of 23 species of perennial flowering plants in the family Primulaceae. Cyclamen species are native to Europe and the Mediterranean Basin east to Iran, with one species in Somalia. They grow from tubers and are valued for their flowers with upswept petals and variably patterned leaves. (Wikipedia)' },
     { id: 2, name: 'alyssum', type: 'flowers', image: 'img/alyssum.jpg', 
        description: 'Alyssum is a genus of about 100–170 species of flowering plants in the family Brassicaceae, native to Europe, Asia, and northern Africa, with the highest species diversity in the Mediterranean region. The genus comprises annual and perennial herbaceous plants or (rarely) small shrubs, growing to 10–100 cm tall, with oblong-oval leaves and yellow or white flowers (pink to purple in a few species). (Wikipedia)'  },
     { id: 3, name: 'dianthus', type: 'flowers', image: 'img/dianthus.jpg', 
        description: 'Dianthus is a genus of about 300 species of flowering plants in the family Caryophyllaceae, native mainly to Europe and Asia, with a few species extending south to north Africa, and one species (D. repens) in arctic North America. Common names include carnation (D. caryophyllus), pink (D. plumarius and related species) and sweet william (D. barbatus).' },
     { id: 4 ,name: 'sweet william', type: 'flowers', image: 'img/sweetwilliam.jpg', 
        description: 'Dianthus barbatus (Sweet William) [2] is a species of Dianthus native to southern Europe and parts of Asia which has become a popular ornamental garden plant. It is a herbaceous biennial or short-lived perennial plant growing to 13–92 cm tall, with flowers in a dense cluster of up to 30 at the top of the stems. Each flower is 2–3 cm diameter with five petals displaying serrated edges. Wild plants produce red flowers with a white base, but colours in cultivars range from white, pink, red, and purple to variegated patterns. The exact origin of its English common name is unknown but first appears in 1596 in botanist John Gerard\'s garden catalogue.' },
     { id: 5, name: 'juncus', type: 'flowers', image: 'img/juncus.jpg', 
        description: 'Juncus is a genus of monocotyledonous flowering plants, commonly known as rushes. It is the largest genus in the family Juncaceae, containing around 300 species.' },
     { id: 6, name: 'kale', type: 'flowers', image: null, description: ''   },
     { id: 7, name: 'maidenhair', type: 'flowers', image: null, description: '' },
     { id: 8, name: 'dracaena', type: 'flowers', image: null, description: ''   },
     { id: 9, name: 'creeping jenny', type: 'flowers', image: null, description: '' },
     { id: 10, name: 'English ivy', type: 'flowers', image: null, description: ''   },
     { id: 11, name: 'tipu tree', type: 'trees', image: null, description: ''},
     { id: 12, name: 'cathedral oak', type: 'trees', image: null, description: ''},
     { id: 13, name: 'cottonwood', type: 'trees', image: null, description: ''},
     { id: 14, name: 'tru-green elm', type: 'trees', image: null, description: '' },
     { id: 15, name: 'camphor', type: 'trees', image: null, description: '' },
     { id: 16, name: 'shumard red oak', type: 'trees', image: null, description: '' },
     { id: 17, name: 'azaleas', type: 'shrubs', image: 'img/azaleas.jpg', 
        description: 'Azaleas are flowering shrubs in the genus Rhododendron, particularly the former sections Tsutsuji (evergreen) and Pentanthera (deciduous). Azaleas bloom in spring, their flowers often lasting several weeks. Shade tolerant, they prefer living near or under trees. They are part of the family Ericaceae.' },
     { id: 18, name: 'redbud', type: 'shrubs', image: 'img/redbud.jpg', 
        description: 'Cercis is a genus of about 10 species in the subfamily Caesalpinioideae of the pea family Fabaceae,[2] native to warm temperate regions. It contains small deciduous trees or large shrubs commonly known as redbuds.[5] They are characterised by simple, rounded to heart-shaped leaves and pinkish-red flowers borne in the early spring on bare leafless shoots, on both branches and trunk ("cauliflory").' },
     { id: 19, name: 'foxtail', type: 'shrubs', image: 'img/foxtail.jpg', 
        description: 'Asparagus aethiopicus, Sprenger\'s Asparagus, is a plant native to the Cape Provinces and the Northern Provinces of South Africa. Often used as an ornamental plant, it is considered an invasive weed in many locations. Asparagus fern and foxtail fern are common names; however, it is unrelated to true ferns.'},
     { id: 20, name: 'monrovia', type: 'shrubs', image: null, description: ''},
     { id: 21, name: 'jatropha', type: 'shrubs', image: null, description: ''},
     { id: 22, name: 'thryallis', type: 'shrubs', image: null, description: ''}
 ];